[package]
name = "example-facet-native"
version = "0.1.0"
edition = "2021"
description = "Example Native Facet - Counter Demo"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18"
borsh = "0.10"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
